{{-- resources/views/emails/admin-bank-transfer-notification.blade.php --}}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>New Bank Transfer Request - {{ config('app.name') }}</title>
</head>

<body style="margin: 0; padding: 0; background-color: #f2f2f2; font-family: Helvetica, Arial, sans-serif; color: #0C3A30;">

  <table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f2f2f2" style="padding: 30px 0;">
    <tr>
      <td align="center">
        <table width="600" cellpadding="0" cellspacing="0" bgcolor="#ffffff" style="border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">

          <!-- Header -->
          <tr>
            <td style="background-color: #8bc905; padding: 30px 20px; text-align: center;">
              <img src="https://res.cloudinary.com/dswwq3xks/image/upload/v1774272450/chartmasterlogo1_z25kgc.png" alt="Chartmasters Circle" style="height: 80px; width: auto; display: block; margin: 0 auto;">
              <p style="color: #0C3A30; font-size: 14px; margin: 10px 0 0 0; font-weight: bold;">ADMIN NOTIFICATION</p>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding: 40px 30px; font-size: 16px; line-height: 1.6; color: #0C3A30;">
              <p style="margin: 0 0 15px 0; font-size: 18px; font-weight: bold; color: #0C3A30;">
                🔔 New Bank Transfer Request
              </p>

              <p style="margin: 0 0 15px 0;">
                A new bank transfer request has been generated by a user.
              </p>

              <!-- User Details -->
              <div style="background-color: #f8f9fa; padding: 15px 20px; margin: 15px 0; border-radius: 4px;">
                <p style="margin: 0 0 5px 0; font-weight: bold; color: #0C3A30;">👤 User Details</p>
                <table width="100%" cellpadding="5" cellspacing="0" style="font-size: 14px;">
                  <tr>
                    <td width="30%" style="font-weight: bold;">Name</td>
                    <td>{{ $user->name }}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Email</td>
                    <td>{{ $user->email }}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Country</td>
                    <td>{{ $user->country ?? 'Not specified' }}</td>
                  </tr>
                </table>
              </div>

              <!-- Transfer Details -->
              <div style="background-color: #e8f5e9; padding: 15px 20px; margin: 15px 0; border-radius: 4px; border-left: 4px solid #8bc905;">
                <p style="margin: 0 0 5px 0; font-weight: bold; color: #0C3A30;">💰 Transfer Details</p>
                <table width="100%" cellpadding="5" cellspacing="0" style="font-size: 14px;">
                  <tr>
                    <td width="30%" style="font-weight: bold;">Amount</td>
                    <td><strong>${{ number_format($amount, 2) }}</strong></td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Reference Code</td>
                    <td><strong style="background-color: #ffffff; padding: 2px 10px; border-radius: 4px; letter-spacing: 1px;">{{ $bankTransfer->reference_code }}</strong></td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Country</td>
                    <td>{{ $bankTransfer->country }}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Bank</td>
                    <td>{{ $bankTransfer->bank_name }}</td>
                  </tr>
                  <tr>
                    <td style="font-weight: bold;">Account Number</td>
                    <td>{{ $bankTransfer->account_number }}</td>
                  </tr>
                </table>
              </div>

              <!-- Action Required -->
              <div style="background-color: #fff3cd; border-left: 4px solid #ffc107; padding: 15px 20px; margin: 20px 0; border-radius: 4px;">
                <p style="margin: 0 0 8px 0; font-weight: bold; color: #856404;">🎯 Actions Required</p>
                <ul style="margin: 0; padding-left: 20px; color: #856404; font-size: 14px;">
                  <li style="margin-bottom: 5px;">Verify the user's account</li>
                  <li style="margin-bottom: 5px;">Prepare bank account details for the user</li>
                  <li style="margin-bottom: 5px;">Send the details to the user via email</li>
                  <li>Monitor for the transfer</li>
                </ul>
              </div>

              <div style="text-align: center; margin: 25px 0;">
                <a href="{{ $adminUrl ?? route('admin.deposits.pending') }}" style="display: inline-block; background-color: #0C3A30; color: #ffffff; padding: 14px 28px; border-radius: 6px; text-decoration: none; font-weight: bold; font-size: 16px;">
                  👀 View Pending Deposits
                </a>
              </div>

              <p style="margin: 0 0 20px 0; font-size: 14px; color: #6c757d;">
                This request is pending admin action.
              </p>

              <p style="margin-top: 40px; font-size: 14px;">
                Regards,<br>
                <strong>The Chartmasters Circle Team</strong>
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background-color: #f2f2f2; text-align: center; padding: 20px; font-size: 12px; color: #0C3A30;">
              &copy; {{ date('Y') }} Chartmasters Circle. All rights reserved.
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>

</body>

</html>